config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
  }

  root'home#top'
  get 'home/top' => 'home#top'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
    member do
      put 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    end
  end

  resources :posts do
    resource :thanks, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    resource :tags, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i(facebook google_oauth2)

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :thanks, dependent: :destroy
  has_many :follower, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followed, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  attachment :profile_image, destroy: false

  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true, unless: :uid?
  validates :introduction, length: { maximum: 150 }

  # is_deletedがfalseの場合は有効会員(ログイン可能)
  def active_for_authentication?
    super && (is_deleted === false)
  end

  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを解除する
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # すでにフォロー済みであればtureを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  private

  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    # 既存ユーザーの場合
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      # set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      # 新規登録の場合
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  # callbackが失敗した場合
  def failure
    redirect_to root_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
        flash[:error] = "お客様は退会済みです。お手数ですが、別のメールアドレスで再度ご登録ください。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "※メールアドレスとパスワードが一致しません。"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_user

  def show
    @posts = @user.posts.page(params[:page]).per(4)
    @posts_all = Post.all
    @follow_users = @user.following_user
    @follower_posts = @posts_all.where(user_id: @follow_users).order("created_at DESC")
  end

  def edit
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def withdraw
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :profile_image, :phone_number, :user_type)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_follow.html.erb
<% if user_signed_in? %>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to 'フォロー解除', user_relationships_path(user), method: :delete, class: "far fa-user btn btn-danger" %>
    <% else %>
      <%= link_to 'フォロー', user_relationships_path(user), method: :POST, class: "fas fa-user btn btn-primary" %>
    <% end %>
  <% else %>
    <%= link_to user_path(current_user), class: "btn btn-default btn-sm" do %>
        <i class="fas fa-user"></i>プロフィール
    <% end %>
  <% end %>
<% end %>

app/views/users/_index.html.erb
<% user.each do |user| %>
<div class="index">
  <%= link_to user_path(user) do %>
    <%= attachment_image_tag(user, :profile_image, size:'80x80', fallback: "no_image.jpg", size:'80x80' , class: "img-rounded-opacity")%>
  <% end %>
  <div class="index-info">
    <div class="post-user">
      <strong class="user-name"><%= user.name %></strong>
      <%= render "users/follow", user: user %>
    </div>
    <div class="follows">
      <span>フォロー：<%= link_to user.follower.count, user_follows_path(user) %></span> | <span>フォロワー：<%= link_to user.followed.count, user_followers_path(user) %></span>
    </div>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
	<h2 class="section-ttl">プロフィール編集</h2>
	<%= form_for(@user, url: user_path) do |f| %>
		<table class="user_info user_form">
			<tbody>
				<tr>
					<td><%= attachment_image_tag @user, :profile_image, id: :img_prev, fallback: "no_image.jpg", size:"250x250" %></td>
					<td><%= f.attachment_field :profile_image, id: :image %></td>
				</tr>
				<tr>
					<td><%= f.label :name, 'ニックネーム' %></td>
					<td colspan="2"><%= f.text_field :name, :placeholder =>"#{@user.name}" , class: "name form-control" %><span class="help-block"></span></td>
				</tr>
				<tr>
					<td><%= f.label :email, "メール" %></td>
					<td colspan="2"><%= f.email_field :email, autocomplete: "email", :placeholder =>"#{@user.email}", class: "email form-control" %><span class="help-block"></span></td>
				</tr>
				<tr>
					<td><%= f.label :phone_number, "電話番号" %></td>
					<td colspan="2"><%= f.text_field :phone_number, placeholder: "電話番号", class: "phone_number form-control" %><span class="help-block"></span></td>
				</tr>
				<tr>
					<td><%= f.label :user_type, "ユーザータイプ" %></td>
					<td colspan="2"> <%= f.select :user_type, {'個人': 1, '団体': 2}, { include_blank: '選択してください'}, { class: 'form-control' , required: true, :placeholder =>"#{@user.user_type}" } %>
						<span class="help-block"></span></td>
				</tr>
				<tr>
					<td><%= f.label :introduction, "自己紹介文" %></td>
					<td colspan="2"><%= f.text_area :introduction, autofocus: true, autocomplete: "introduction", placeholder: "コメント入力", class: "introduction form-control" %></td>
				</tr>
				<tr>
					<td colspan="2"><%= f.submit "編集内容を保存する", class: "btn btn-primary" %></td>
					<td><%= link_to "退会する", withdraw_user_path(current_user), method: :put, "data-confirm" => "本当にこのアカウントを削除しますか？　※投稿されたデータおよび個人情報が全て削除されます。",  class: "btn btn-danger" %></td>
				</tr>
			</tbody>
		</table>
	<% end %>
  <div class="margin">
    <%= link_to "戻る", user_path, class: "btn btn-default btn-xm" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="container">
      <h1>プロフィール</h1>
      <div class="clearfix margin-top">
        <div class="pull-left col-md-3 col-sm-12">
          <%= attachment_image_tag @user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size:"200x200", class: "img-rounded" %>
        </div>
        <div class="pull-left col-md-9 col-sm-12">
          <h3><%= @user.name %></h3>
          <div>
          <%= @user.introduction %>
          </div>
          <div>
            <p>投稿数：<%= @user.posts.count %><br>
              ありがとうの合計：<%= @user.thanks.count %>
            </p>
          </div>
          <div>
            <p>フォロー：<%= link_to @user.follower.count, user_follows_path(@user) %>　フォロワー：<%= link_to @user.followed.count, user_followers_path(@user) %></p>
          </div>
          <% if current_user == @user %>
            <%= link_to "プロフィールを編集する", edit_user_path(@user), class: "btn btn-primary" %>
          <% end %>
        </div>
        <% render "users/follow", user: @user %>
      </div>
    </div>
  </div>

  <div class="margin-top container">
    <div class="container">
      <% if @user == current_user %>
        <ul class="nav nav-tabs">
          <li class="active"><a href="#sampleContentA" data-toggle="tab">投稿 <i class="fas fa-user"></i></a></li>
          <li><a href="#sampleContentB" data-toggle="tab">友達の投稿 <i class="fas fa-user-friends"></i></a></li>
        </ul>

        <div class="tab-content margin-top">
          <div class="tab-pane active" id="sampleContentA">
            <% if @posts.exists? %>
              <%= render 'posts/index',posts: @posts %>
            <% else %>
              <p>投稿がありません。</p>
            <% end %>
          </div>

          <% if @user == current_user %>
            <div class="tab-pane" id="sampleContentB">
              <% if current_user.follower.exists? %>
                <%= render 'posts/index',posts: @follower_posts %>
              <% else %>
                <p>フォロー<i class="fas fa-user-friends"></i>したいユーザーを見つけよう！</br>
                    <%= link_to "投稿一覧ページ", posts_path %>を確認する
                </p>
              <% end %>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="row">
          <div class="new-posts">
            <h2 class="title">投稿一覧</h2>
            <%= render 'posts/index',posts: @posts %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>