config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
  }

  root'home#top'
  get 'home/top' => 'home#top'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
    member do
      put 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    end
  end

  resources :posts do
    resource :thanks, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    resource :tags, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :thanks, dependent: :destroy
  has_many :thank_users, through: :thanks, source: :user
  has_many :tag_maps, dependent: :destroy
  has_many :tags, dependent: :destroy
  attachment :image, destroy: false
  validates :image, presence: true
  validates :content, presence: true, length: { maximum: 200 }
  has_one :spot, dependent: :destroy
  accepts_nested_attributes_for :spot

  def thanked_by?(user)
    thanks.where(user_id: user.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, length: { maximum: 150 }, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :post
  geocoded_by :address
  after_validation :geocode
  validates :address, presence: true
  validate :check_latitude
  validate :check_longitude

  def check_latitude
    if latitude.nil?
      errors.add(:latitude, "マップから別の場所を選択してください。（または英語で記入してください）")
    end
  end

  def check_longitude
    if longitude.nil?
      errors.add(:longitude, "マップから別の場所を選択してください。（または英語で記入してください）")
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  # has_many :tag_maps, dependent: :destroy, foreign_key: "tag_id"
  # has_many :posts, through: :tag_maps
  validates :tag_name, length: { maximum: 20 }
  belongs_to :post
  def self.search(search)
    return Tag.all unless search
    Tag.where('tag_name LIKE(?)', "%#{search}%")
  end
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/thank.rb
class Thank < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i(facebook google_oauth2)

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :thanks, dependent: :destroy
  has_many :follower, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followed, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  attachment :profile_image, destroy: false

  validates :name, length: { maximum: 20, minimum: 2 }, uniqueness: true, unless: :uid?
  validates :introduction, length: { maximum: 150 }

  # is_deletedがfalseの場合は有効会員(ログイン可能)
  def active_for_authentication?
    super && (is_deleted === false)
  end

  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを解除する
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # すでにフォロー済みであればtureを返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @user = User.order(updated_at: :desc).limit(10)
    @posts = Post.all.page(params[:page]).per(8).order(created_at: :desc)
    gon.my_private_key = ENV["GOOGLE_API_KEY"]
    lat_lng = []
    i = 0
    @posts.each do |post|
      if post.spot
        lat_lng[i] = { latitude: "#{post.spot.latitude}", longitude: "#{post.spot.longitude}" }
        i += 1
      end
    end
    gon.lat_lng = lat_lng
  end

  def show
    @post = find_post_by_id
    @post_comment = PostComment.new
    @post_comments = @post.post_comments
    lat_lng = []
    lat_lng[0] = { latitude: "#{@post.spot.latitude}", longitude: "#{@post.spot.longitude}" }
    gon.lat_lng = lat_lng
  end

  def edit
    @post = find_post_by_id
    if current_user.id != @post.user_id
      redirect_to posts_path
    end
  end

  def new
    @post = Post.new
    @post.build_spot
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      tags = Vision.get_image_data(@post.image)
      tags.each do |tag|
        @post.tags.create(tag_name: tag)
      end
      redirect_to posts_path(@post)
    else
      render 'new'
    end
  end

  def update
    @post = find_post_by_id
    if @post.update(post_params)
      flash[:success] = "写真が更新されました！"
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = find_post_by_id
    @post.destroy
    redirect_to posts_url
  end

  private

  def post_params
    params.require(:post).permit(:image, :garbage_count, :content, :join_amount, :published_at, spot_attributes: [:address, :latitude, :longitude])
  end

  def find_post_by_id
    Post.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
  end
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @post.thanks.create(user_id: current_user.id)
  end

  def destroy
    @post = Post.find(params[:post_id])
    thank = current_user.thanks.find_by(post_id: @post.id)
    thank.destroy
  end

  private

  def thank_params
    params.require(:post).permit(:user_id, :post_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_user

  def show
    @posts = @user.posts.page(params[:page]).per(4)
    @posts_all = Post.all
    @follow_users = @user.following_user
    @follower_posts = @posts_all.where(user_id: @follow_users).order("created_at DESC")
  end

  def edit
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def withdraw
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :profile_image, :phone_number, :user_type)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/posts/_detail.html.erb
<td>
  <div class="post_img">
      <%= link_to attachment_image_tag(post, :image, size: '100×100',fallback: 'no_image.jpg', class: "img-rounded img")%>
  </div>
</td>
<td>
  <div class="user_info">
    <%= link_to user_path(post.user) do %>
      <%= attachment_image_tag(post.user, :profile_image,  :fill, 70, 70, fallback: "no_image.jpg", class: "img-circle") %>
      <b><%= post.user.name %></b>
    <% end %>
  </div>
</td>
<td class="post_content">
  <div class="post_body">
    <p class="summary"><%= post.content %></p>
  </div>
</td>
<td>
  <% if post.thanked_by?(current_user) %>
    <%= link_to post_thanks_path(post), method: :delete, remote: true do %>
      <i class="fas fa-hand-holding-heart" aria-hidden="true" style="color: red;"></i>
      <%= post.thanks.count %>
    <% end %>
  <% else %>
    <%= link_to post_thanks_path(post), method: :post, remote: true do %>
      <i class="fas fa-hand-holding-heart" aria-hidden="true"></i>
      <%= post.thanks.count %>
    <% end %>
  <% end %>
</td>
<td>
  <span class="pull-right"><%= time_ago_in_words(post.created_at) %>前</span>
</td>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
  <div class="col-xs-6">

    <%= f.label :garbage_count, "拾ったゴミの数" %><br>
    <%= f.select :garbage_count, [*(1..50)], {selected: 1}, class: "garbage_count" %> 個
    <span class="help-block"></span>

    <%= f.label :published_at, "日時" %><br>
    <%= f.date_field :published_at, class: 'form-control' %>
    <span class="help-block"></span>
    <%= f.time_field :published_at, class: 'form-control' %>
    <span class="help-block"></span>

    <%= f.text_area :content, autofocus: true, autocomplete: "content", placeholder: "コメント入力", class: "content form-control" %>
    <span class="help-block"></span>

    <div class="spot margin-top">
    <%= f.fields_for :spot do |s| %>
      <%= s.label :address, "拾った場所(Google Mapで検索)", class: 'spot__title' %>
      <div class="spot_form">
        <div class="col-xs-10">
          <%= s.text_field :address, placeholder: "スポットを入力", id: "address", class: 'spot__text form-control' %>
          <%= s.hidden_field :longitude, id: "longitude" %>
          <%= s.hidden_field :latitude, id: "latitude" %>
        </div>
    <% end %>
        <div class="col-xs-2">
          <input onclick= "codeAddress()" type= "button" value= "検索する" class=" btn btn-info btn-sm"></input>
        </div>
      </div>
    </div>

  </div>
  <div class="col-xs-6">

    <%= attachment_image_tag post, :image, id: :img_prev, fallback: "no-image-icon.jpg", class: "update-img" %>
    <%= f.attachment_field :image, id: :image %>
    <div class= "map margin-top30" id= "map", style= "height: 320px; width: 450px;" ></div>

  </div>

  <div class="flex align-center ">
    <% if request.path_info == new_post_path %>
      <%= f.submit "投稿", class: "btn btn-primary"%>
    <% else %>
      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/posts/_index.html.erb
<% posts.each do |post| %>
<div class="index">
  <%= link_to post_path(post) do %>
    <%= attachment_image_tag post, :image, size: '110x115', class: "img-rounded-opacity"%>
  <% end %>
  <div class="index-info">
    <div class="post-user">
      <%= link_to user_path(post.user) do %>
        <%= attachment_image_tag(post.user, :profile_image, size:'40x40', fallback: "no_image.jpg", size:'40x40', class: "img-rounded-opacity")%>
        <strong class="user-name" ><%= post.user.name %></strong>
      <% end %>
        <span><%= post.created_at.strftime('%Y/%m/%d') %></span>
        <i class="far fa-clock"></i>
        <span><%= time_ago_in_words(post.created_at) %>前</span>
    </div>
    <p class="post-user-content"><%= post.content.truncate(20) %></p>
  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
	<h1>投稿を編集する</h1>
	<%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="container margin-top30">
  <div class="row">
    <div class="show">
      <div class="show__maps center-block" id="show_map" style="height: 450px;"></div>
    </div>
    <div class="col-md-8">
      <div class="info">
        <h2 class="title">新着投稿</h2>
        <%= render 'index',posts: @posts %>
        <%= paginate @posts %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="info">
        <h2 class="title">新着ユーザー</h2>
        <%= render 'users/index',user: @user %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container margin">
	<div class="row">
		<h2>活動を投稿する</h2>
	    <%= render 'form', post: @post, url: posts_path %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container post-show">
  <div class="row">
    <div class="clearfix container">

      <div class="col-md-6 col-xs-12">
        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-6">
          <%= link_to user_path(@post.user) do %>
            <%= attachment_image_tag @post.user, :profile_image, fallback: "no_image.jpg", size: "50x50", class: "profile-image-icon pull-left" %>
            <h5 class="pull-left profile-name"><%= @post.user.name %></h5>
          <% end %>
        </div>
        <div class="col-xs-7 col-sm-7 col-md-7 col-lg-6">
          <div class="post_<%= @post.id %> pull-right">
            <%= render 'thanks/thank', post: @post %>
          </div>
        </div>
        <%= attachment_image_tag @post, :image, format: "jpeg", fallback: "no_image.jpg",  class: "img-rounded img-show center-block" %>
        <div class="col-xs-10 margin col-xs-offset-1">
          <h4><%= @post.content %></h4>
          <% @post.tags.each do |tag| %>
            <span class="label"><%= tag.tag_name %></span>
          <% end %>
        </div>
        <div class="pull-right">
            <small>投稿日 <%= @post.created_at.strftime('%Y/%m/%d/ %H:%M') %></small>
        </div>
      </div>

      <div class="col-md-6 col-xs-12 margin">
        <div class="col-xs-offset-1">
          <div class="col-xs-5">拾ったゴミの数</div>
          <div class="col-xs-7"><%= @post.garbage_count %></div>

          <div class="col-xs-12 l-md-3 margin">
            <% if @post.user == current_user %>
              <%= link_to '編集', edit_post_path(@post), class: "btn-sm btn-primary glyphicon glyphicon-pencil" %>
              <%= link_to '', @post, method: :delete, data:{confirm: '本当に消しますか？' }, class: "btn-default btn glyphicon glyphicon-trash" %>
            <% end %>
          </div>
        </div>
        <div class="show__maps map margin center-block" id="show_map", style= "height: 320px; width: 450px;"></div>
      </div>

      <div class="col-md-8 col-md-offset-2">
        <%= render 'post_comments/comments', post_comments: @post_comments %>
        <% if user_signed_in? %>
          <%= form_with(model: [@post, @post_comment], remote: true) do |f| %>
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントを投稿しましょう！" %>
            <%= f.submit "送信", class: "btn btn-primary mt-20 pull-right" %>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>

  <div class="margin">
    <%= link_to "戻る", posts_path, class: "btn btn-default btn-xm" %>
  </div>
</div>

app/views/thanks/_thank.html.erb
<% if user_signed_in? %>
  <% if post.thanked_by?(current_user) %>
    <%= link_to post_thanks_path(post), method: :delete, remote: true, class: "option__thank-on box" do %>
      <i class="fas fa-hand-holding-heart"></i><%= post.thanks.count %> ありがとう
    <% end %>
  <% else %>
    <%= link_to post_thanks_path(post), method: :post, remote: true, class: "option__thank-off box" do %>
      <i class="fas fa-hand-holding-heart"></i><%= post.thanks.count %> ありがとう
    <% end %>
  <% end %>
<% end %>

app/views/thanks/create.js.erb
$(".post_<%= @post.id %>").html("<%= j(render 'thanks/thank',  post: @post ) %>")

app/views/thanks/destroy.js.erb
$(".post_<%= @post.id %>").html("<%= j(render 'thanks/thank',  post: @post ) %>")